export const mattersData = [
  { subject: 'UC5', teacher: 'Roberto' },
  { subject: 'UC6', teacher: 'Roberto' },
  { subject: 'Matemática', teacher: 'Silvia' },
  { subject: 'Projeto de Vida', teacher: 'Silvia' },
  { subject: 'Trabalho e Economia', teacher: 'Patricia' },
  { subject: 'Tecnologia', teacher: 'Patricia' },
  { subject: 'Compostos Agrícolas', teacher: 'Suemy' },
  { subject: 'Educação Física', teacher: 'Vinicius' },
  { subject: 'Artes', teacher: 'Carol' },
  { subject: 'Português', teacher: 'Darque' },
  { subject: 'Inglês', teacher: 'Luis Gustavo' },
  { subject: 'Orientação de Estudos', teacher: 'Dina' },
  { subject: 'Manipulação de Genes', teacher: 'Telma' },
  { subject: 'Alimentação Sustentável', teacher: 'Joelma' },
];